name: Deploy to Hostinger

on:
  push:
    branches:
      - main  # ou o nome da sua branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'  # Substitua pela versÃ£o de PHP utilizada na sua API

    - name: Install dependencies
      run: composer install  # Se vocÃª estiver usando o Composer para gerenciar as dependÃªncias

    - name: Deploy to Hostinger
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ${{ secrets.FTP_HOST }}  # Nome de usuÃ¡rio e endereÃ§o do servidor (host) da Hostinger
        username: ${{ secrets.FTP_USER }}  # Nome de usuÃ¡rio FTP/SFTP da Hostinger
        password: ${{ secrets.FTP_PASSWORD }}  # Senha FTP/SFTP da Hostinger
        local-dir: .api  # DiretÃ³rio do seu projeto a ser enviado para o servidor
        remote-dir: /public_html/api  # DiretÃ³rio no servidor onde a API serÃ¡ implantada



# on: 
#   push: 
#     branchs:
#     - main
# name: ðŸš€ Deploy website on push
# jobs:
#   web-deploy:
#     name: ðŸŽ‰ Deploy
#     runs-on: ubuntu-latest
#     steps:
#     - name: ðŸšš Get latest code
#       uses: actions/checkout@v3
    
#     - name: ðŸ“‚ Sync files
#       uses: SamKirkland/FTP-Deploy-Action@v4.3.4
#       with:
#         server: ${{secrets.ftp_host}}
#         username: ${{secrets.ftp_user}}
#         password: ${{ secrets.ftp_password }}
#         server-dir: public_html/api/

